### ISSUE TITLE
RK3128H Is Supported?

### ISSUE THREAD

**Issue by TrungKenbi** [paolosabatino/multitool#3]
Box: Android TV Box Vinabox X2
Link: https://www.annguyenco.com/products/android-tv-box-vinabox-x2
CPU: RK3128H
RAM: 1GB 
ROM: 8GB
![photo_2023-04-08_16-13-09](https://user-images.githubusercontent.com/15015724/230713616-569240ca-bb8b-4bdc-91de-e919320d63e6.jpg)

**Comment by TrungKenbi** [comment]
dts — rk3128x.dtsi: http://www.atmcu.com/2063.html

**Comment by paolosabatino** [comment]
Nope.
Not an issue, closing

**Comment by TrungKenbi** [comment]
@paolosabatino notify with me when RK3128H is supported. Many thanks !
